### ISSUE TITLE
Missing Checkpoint

### ISSUE THREAD

**Issue by Ziruiwang409** [ZCMax/ScanReason#6]
Hello, 

Thanks @ZCMax for the amazing work. When I want to tryout the training script, I came across the following pretrained checkpoint. 

parser.add_argument(
        "--version", default="/mnt/petrelfs/zhuchenming/LLaVA/checkpoints/llava3d-v1.5-7b-task-lora-v3-voxelize-region-1-4-tuning-mmscan/merged/llava3d-v1.5-7b-task-v3"
    )

I m wondering where can I find the specific file here? Appreciate your help!

**Comment by Ziruiwang409** [comment]
nvm, I find it. Thanks

**Comment by NorthSummer** [comment]
> nvm, I find it. Thanks

Hi, could you please tell me where you find the pretrained weights? Thx

**Comment by NorthSummer** [comment]
> nvm, I find it. Thanks

Hi, I wonder have you found the checkpoint file for "point encoder", i.e. the "bu_detr_backbone"?

**Comment by Samir55** [comment]
Hi @Ziruiwang409, I was wondering if you could provide where to find the checkpoint for the point encoder named butd_detr_scanrefer_backbone.pth. It would be greatly appreciated.

**Comment by arebs23** [comment]
Hi  @Ziruiwang409,I was also wondering where i can find the link to the checkpoint butd_detr_scanrefer_backbone.pth. Thanks
